name: Jekyll site CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hakierspejs/jekyll-screenshot-github-action@1.0
    - uses: actions/upload-artifact@v1
      with:
       name: screenshot
       path: /home/runner/work/_temp/_github_home/screenshot.png
